[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
# eth-rpc-url = "http://8.218.239.44:8545"
# eth-rpc-url = "https://eth-mainnet.g.alchemy.com/v2/-TWiuJwba-4Oiw3G9jtF18zhFDam5taO"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config